### ISSUE TITLE
Not working with Highcharts 4.1.4 - objectEach is not a function

### ISSUE THREAD

**Issue by white91wolf** [blacklabel/custom_events#126]
i just tested this extension but it wont run in my system where i have to use Highcharts 4.1.4.
I edited the example jsfiddle for this project where i just changed the highchart.js with the 4.1.4 and there is the same error in the console.. i think the function objectEach wont be the only one.. just the first one which gets called.

https://jsfiddle.net/pcksqnfo/

Uncaught TypeError: objectEach is not a function
    at Object.getEventsProtoMethods (customEvents.js:129)
    at Object.init (customEvents.js:142)
    at customEvents.js:530
    at customEvents.js:20
    at customEvents.js:22

**Comment by white91wolf** [comment]
just changed the versions up to 5.0.9 its still not working... so what is the real lastest version?? or is there some bug? we need this really but we are "stuck" at Highcharts 4.1.4

**Comment by sebastianbochan** [comment]
Hi @white91wolf,
Thank you for reporting! 

The `custom-events` module uses functions like `objectEach` and `isArray` which are added since 6.0 version. I added back-compatibility declarations to the plugin.
